// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8OiieD5vbG3rLGRtCt506HNp4RVCya8',
    appId: '1:934430367553:web:7f1ce5202af1f9522b4bc0',
    messagingSenderId: '934430367553',
    projectId: 'unihub-741ad',
    authDomain: 'unihub-741ad.firebaseapp.com',
    storageBucket: 'unihub-741ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHeiPgmW7Qzdn20uhR-y0iAvCu-p_7yw',
    appId: '1:934430367553:android:8391144a833ff2cc2b4bc0',
    messagingSenderId: '934430367553',
    projectId: 'unihub-741ad',
    storageBucket: 'unihub-741ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq1U_Lh8ED4peoCnbZSD17TQateNIBJCI',
    appId: '1:934430367553:ios:ee70e634423ebaa52b4bc0',
    messagingSenderId: '934430367553',
    projectId: 'unihub-741ad',
    storageBucket: 'unihub-741ad.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq1U_Lh8ED4peoCnbZSD17TQateNIBJCI',
    appId: '1:934430367553:ios:ee70e634423ebaa52b4bc0',
    messagingSenderId: '934430367553',
    projectId: 'unihub-741ad',
    storageBucket: 'unihub-741ad.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8OiieD5vbG3rLGRtCt506HNp4RVCya8',
    appId: '1:934430367553:web:f5742a18357948c62b4bc0',
    messagingSenderId: '934430367553',
    projectId: 'unihub-741ad',
    authDomain: 'unihub-741ad.firebaseapp.com',
    storageBucket: 'unihub-741ad.firebasestorage.app',
  );
}
